### ISSUE TITLE
HIBP now requires an API key

### ISSUE THREAD

**Issue by Slad3G** [Techno-Hwizrdry/checkpwnedemails#3]
Thanks for the hard work and great script. HIBP now requires v3 of the API and an API key:
https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/

Any chance the script could be updated to include these?

Thanks again,

SG

**Comment by Techno-Hwizrdry** [comment]
Yes, an updated version of checkpwnedemails is coming soon.  Stay tuned. :)

**Comment by Techno-Hwizrdry** [comment]
Hi Slade,

I would like to give you an update on my progress.  I have just verified my
email to get a HIBP API key, but I have hit a wall.  After I verfied my
email, I got the following message on the confirmation page:   "New
subscriptions to the HIBP API are temporarily disabled. This should only be
momentary, check back again soon."

I will keep checking HIBP to see if subscriptions have been re-enabled.
Once I have an API key, I will begin to make the necessary updates to
checkpwnedemails.py.

Cheers!

**Comment by Slad3G** [comment]
Alexan,

I do have a HIBP API key and would be happy to test things for you.

Best,

Slade G

**Comment by Techno-Hwizrdry** [comment]
Hi Slade,

I have just pushed my latest version of checkpwnedemails.py to my github.
It is now compatible with v3 of the HaveIBeenPwned API.  Let me know if you
have any questions, comments, or concerns.

And thank you for your patience.  :)

Cheers,
       Alexan
