### ISSUE TITLE
Unable to use -o option, script is only parsing single email

### ISSUE THREAD

**Issue by Mr-P-D** [Techno-Hwizrdry/checkpwnedemails#6]
┌──(kali㉿kali)-[~/checkpwnedemails]
└─$ python3 checkpwnedemails.py -a hibp.txt -i emails.txt -o op.txt

Traceback (most recent call last):
  File "/home/kali/checkpwnedemails/checkpwnedemails.py", line 239, in <module>
    main()
  File "/home/kali/checkpwnedemails/checkpwnedemails.py", line 235, in main
    write_results_to_file(opts.output_path, results, opts)
  File "/home/kali/checkpwnedemails/checkpwnedemails.py", line 190, in write_results_to_file
    outfile.write(tab_delimited_string(r) + '\n')
  File "/home/kali/checkpwnedemails/checkpwnedemails.py", line 148, in tab_delimited_string
    flat_data_classes = [str(x) for x in d[DATACLASSES]]
TypeError: string indices must be integers

**Comment by Techno-Hwizrdry** [comment]
Hello @Mr-P-D ,

The script was not properly handling rate limit responses from the HIBP API.  For lowest pricing tier, the rate limit needs to be set to 6.0.    (60 / 10 RPS = 6.0).   Refer to the following post for more RPM (requests per minute) details:  https://www.troyhunt.com/the-have-i-been-pwned-api-now-has-different-rate-limits-and-annual-billing/

I have just pushed some new changes to the checkpwnedemails.py  script in the 'master' branch.  These changes address the proper handling of rate limit responses from the API.  Also, the script uses a .conf file to store the API key and rate limit.

For more details, regarding the new changes and setup, please refer to the README.md.

Cheers!

**Comment by Mr-P-D** [comment]
thanks alot, i will give it a try and confirm

**Comment by Techno-Hwizrdry** [comment]
Hi @Mr-P-D ,

Just following up with you.  Have you given it a try yet?  If so, how did it go?

**Comment by Mr-P-D** [comment]
Hi, i checked yesterday had same issue, i will recheck tomorrow

**Comment by Techno-Hwizrdry** [comment]
Are you running it in the virtualenv?  Also, can you provide the exact command you're using at the command line?

**Comment by Techno-Hwizrdry** [comment]
> Hi, i checked yesterday had same issue, i will recheck tomorrow

Have you had a chance to pull the latest changes and try again?  Also:

Are you running it in the virtualenv? Also, can you provide the exact command you're using at the command line?

**Comment by Techno-Hwizrdry** [comment]
No response.  I assume the latest fixes has solved the issue.  If not, let me know and I will reopen this issue.  Cheers!

**Comment by Techno-Hwizrdry** [comment]
No response. I assume the latest fixes has solved the issue. If not, let me know and I will reopen this issue. Cheers!

**Comment by Mr-P-D** [comment]
Apologies for late response, got caught up in work load, yes, latest fixes has solved everything and it is now working very smooth, thanks alot

**Comment by Mr-P-D** [comment]
One thing which standout to me i have purchase 50 RPM API, after setting the limit to 1.2 in conf file it still took 4 minutes to go through 50 emails, any ideas what might be causing this ?
